version: '2'
services:
  nginx: 
    image: belajar-nginx
    container_name: belajar-nginx
    ports:
      -80:80

  node:
   image: belajar-node
   container_name: belajar-node
   ports:
      -3001:3001
   volumes: /root/belajar-docker/coba-node
expose: 3001:80
volumes:
  tmp: