version: '2'
services:
  nginx: 
    image: belajar-nginx
    container_name: belajar-nginx
    restart: always
    ports:
      -81:81

  node:
   image: belajar-node
   container_name: belajar-node
   networks_mode: host
   volumes: 
      - /root/belajar-docker/coba-node:/root/belajar-docker/coba-node

volumes:
  tmp: