version: '2'
services:
  nginx: 
    image: nginx
    container_name: belajar-nginx
    restart: always
    network_mode:
      - host
  node:
   image: belajar-node
   container_name: belajar-node
   networks_mode: host
   volumes: 
      - /root/belajar-docker/coba-node:/root/belajar-docker/coba-node

volumes:
  tmp: